AllCops:
  TargetRubyVersion: 3.1.4
  SuggestExtensions: false
  Exclude:
    - bin/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    - db/seeds*
    - Gemfile.lock
    - mysql_data/*
    - node_modules/*
    - tmp/*

Style/Documentation:
  Exclude:
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - test/application_system_test_case.rb
    - test/test_helper.rb
