AllCops:
  TargetRubyVersion: 3.1.4
  SuggestExtensions: false
  Exclude:
    - bin/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    - Gemfile.lock
    - mysql_data/*
    - node_modules/*
    - tmp/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
