AllCops:
  TargetRubyVersion: 3.1.4
  SuggestExtensions: false
  Exclude:
    - bin/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    - db/seeds*
    - Gemfile.lock
    - mysql_data/*
    - node_modules/*
    - tmp/*

Style/Documentation:
  Enabled: false
