default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: mysql

development:
  <<: *default
  database: rails_fundamental_development

test:
  <<: *default
  database: rails_fundamental_test

production:
  <<: *default
  database: rails_fundamental_production
